### PR TITLE
Fix a failed db migration

### PR DESCRIPTION
**Pull request by insuyun**
Since current qual page uses functions which are not supported by
sqlite3, current db migration gives an error
e.g sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near
"DROP": syntax error [SQL: u'ALTER TABLE problemsetscore DROP COLUMN
username'] -> because no DROP COLUMN in sqlite3
Therefore, use postgresql to use current migrations.

### CODE REVIEW

**Comment by hyeonseop-lee** [comment]
Thank you for suggestion, this was known issue but not considered critical; postgresql will be nice alternative. As a matter of fact, GoN qual is deployed with postgresql :)

**Comment by insuyun** [comment]
To make people to run your program, you should change your migration script to work on sqlite3 or change default database to postgresql.  Current migration script does not work on sqlite3.

**Comment by hyeonseop-lee** [comment]
Yepp, I'm working, plz give me minutes.

**Comment by insuyun** [comment]
근데 한국어로 해도 되잖아?~

**Comment by hyeonseop-lee** [comment]
먼저 영어로 하셨잖아요ㅠ

**Pull request closed without merging**
